language: node_js

notifications:
  email: false
node_js:
  - '12'
install: npm install
after_success:
  - npm run build
  - npm run travis-deploy-once "npm run semantic-release"
  - npm run travis-coveralls
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
